config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "/about", to: "frontend#about", as: :about
  get "/our-mision", to: "frontend#our_mision", as: :mision
  get "/contact", to: "frontend#contact_us", as: :contact
  get "/order/:symphony_id", to: "frontend#new_order", as: :new_order_frontend
  get "/verify-name", to: "frontend#verify_name", as: :verify_name
  post "/hear", to: "frontend#hear", as: :hear
  post "/order", to: "frontend#create_order", as: :create_order
  get :autocomplete_kid_name, to: "frontend#autocomplete_kid_name", as: :autocomplete_kid_name_orders

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :symphonies do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :orders do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple

    end

  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #contact_us
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'


end

app/models/user.rb
require 'elasticsearch/model'
class User < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :create_permalink, on: :create
  rolify
  validates_presence_of :name, :role_ids, :email

  #has_many :posts, dependent: :destroy relation posts
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end

  def rol
    self.roles.first.name
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:rol, :name, :email, :id] , operator: :and }  }, sort: { id: "desc" }, size: User.count }
  end

  #saber la pagina a la que pertenece
  def page(order = :id)
    ((self.class.order(order => :desc).pluck(order).index(self.send(order))+1).to_f / self.class.default_per_page).ceil
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      email: self.email,
      name: self.name,
      rol: self.rol
    }.as_json
  end

  private

  def create_permalink
    self.permalink = self.name.downcase.parameterize+"-"+SecureRandom.hex(4)
  end

end

#User.import

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    users = User.searching(@query).where.not(id: current_user.id)
    @objects, @total = users.page(@current_page), users.size
    redirect_to users_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end
  
  def update
    respond_to do |format|
      update_attributes = user_params.delete_if do |attribute, value|
        case attribute
          when "password"
            value.blank?
          when "password_confirmation"
            value.blank? if user_params.fetch("password").blank?
        end
      end

      if @user.update_attributes(update_attributes)    
        if params.fetch(:commit).eql?("Asignar Rol")
          format.html { redirect_to users_path, :notice => "Rol asignado satisfactoriamente" }
        else
          format.html { redirect_to user_path(@user), :notice => "Usuario actualizado satisfactoriamente" }
        end
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end

    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @user.add_role Role.find(user_params.fetch(:role_ids)).name
        format.html { redirect_to user_path(@user), notice: "Usuario creado satisfactoriamente" }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: "Usuario eliminado satisfactoriamente" 
  end

  def destroy_multiple
    User.destroy redefine_ids(params[:multiple_ids])
    redirect_to users_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role_ids, :encrypted_password)
  end

end

app/views/users/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Módulo de usuarios
		%p Aquí podrá gestionar todos los usuarios del sistema, ofrece opciones para crear, editar, eliminar y visualizar, tambien tiene la opción de asignar roles para controlar el acceso de sus usuarios en la aplicación.

app/views/users/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to users_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @user do |f|
					.row 
						= f.input :name
						= f.input :email
						= f.input :role_ids, collection: Role.all.map { |rol| [rol.name.humanize, rol.id] }, label: false, include_blank: "Selecione un rol"
						= f.input :password
						= f.input :password_confirmation
						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/users/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, User
			= link_to "#modal-#{@user.id}", class: "btn-floating waves-effect waves-light btn-flat tooltipped modal-trigger", "data-position" => "bottom", "data-tooltip" => "Cambiar rol"  do
				= material_icon.md_24.supervisor_account
		- if can? :update, User
			= link_to edit_user_path(@user), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		- @user.as_json(only: ["id", "name", "permalink", "email", "created_at", "sign_in_count", "updated_at", "password"]).each do |attribute, value|
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.#{attribute}")
				.display-value= value

= render "users/modal"

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/users/_listing.html.haml
%tr{ id: "row-#{user.id}" }
	- if can? :destroy_multiple, User
		%td.item-check{style:"width: 10%"}
			= link_to "", user_path(user), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{user.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{user.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{user.id}" }
	%td.hide-on-small-and-down{style:"width: 30%"}
		= link_to "", user_path(user, search: @query), remote: true, class: "show-row"
		%span
			= user.name											
	%td{style:"width: 35%"}
		= link_to "", user_path(user, search: @query), remote: true, class: "show-row"
		%span
			= user.email			 
	%td.hide-on-small-and-down{style:"width: 20%"}
		= link_to "", user_path(user, search: @query), remote: true, class: "show-row"
		%span
			= user.rol.humanize
	%td{style:"width: 5%"}		
		= link_to user_path(user), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/users/_modal.html.haml
.modal{ id: "modal-#{@user.id}"}
	= form_tag user_path(@user),  method: "PUT" do
		.modal-header
			%h4= "Cambiar rol de #{@user.name}"
		.modal-content
			- Role.all.each do |role|
				.radio-button
					= radio_button_tag "user[role_ids]", role.id, false, class: "radio-button__input", id: "radio#{role.id}", :type => "radio", :value => "#{role.id}", :checked => @user.has_role?(role.name)
					= label_tag "user[role_ids]", role.name.humanize, class: "radio-button__label", :for => "radio#{role.id}"
		.modal-footer
			= button_tag "Asignar Rol", :class => "waves-effect waves-light btn", name: 'commit', value: "Asignar Rol"
			= link_to "Cancelar", "", class: "modal-action modal-close waves-effect waves-light btn red"
		

app/views/users/edit.html.haml
= title "Usuarios - editar | #{@user.name}"
= render 'form'

app/views/users/index.html.haml
//change title
= title("Usuario - Listado")

.listing.col.l9.m12.s12
	= link_to new_user_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
		= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |user|
				= render 'listing', user: user
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado usuarios.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"


= link_to new_user_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
	= material_icon.md_24.add.css_class("md-light")

app/views/users/new.html.haml
= title "Usuarios - Nuevo"
= render 'form'

app/views/users/show.html.haml
= title "Usuarios | #{@user.name}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, User
				= link_to user_path(@user), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, User
				= link_to edit_user_path(@user), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to users_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				- @user.as_json(only: ["id", "name", "permalink", "email","created_at", "sign_in_count", "updated_at", "password"], methods: [:rol]).each do |attribute, value|
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.#{attribute}")
						.display-value.fs-body-1.tc-black-2= value.to_s.humanize

app/views/users/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@user.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");