config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "/about", to: "frontend#about", as: :about
  get "/our-mision", to: "frontend#our_mision", as: :mision
  get "/contact", to: "frontend#contact_us", as: :contact
  get "/order/:symphony_id", to: "frontend#new_order", as: :new_order_frontend
  get "/verify-name", to: "frontend#verify_name", as: :verify_name
  post "/hear", to: "frontend#hear", as: :hear
  post "/order", to: "frontend#create_order", as: :create_order
  get :autocomplete_kid_name, to: "frontend#autocomplete_kid_name", as: :autocomplete_kid_name_orders

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :symphonies do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :orders do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple

    end

  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #contact_us
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'


end

app/models/order.rb
#Generado por keppler
require 'elasticsearch/model'
class Order < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :articles
  accepts_nested_attributes_for :articles, reject_if: :all_blank, allow_destroy: true
  validates_presence_of :name, :email, :phone
  validates :phone, numericality: { only_integer: true }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  
  after_commit on: [:update] do
    __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:id, :kid_name, :symphony, :quantity, :name, :email, :phone] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name: self.name,
      email: self.email,
      phone: self.phone
    }.as_json
  end

end
#Order.import

app/controllers/orders_controller.rb
#Generado con Keppler.
class OrdersController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  def index
    orders = Order.searching(@query).all
    @objects, @total = orders.page(@current_page), orders.size
    redirect_to orders_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /orders/1
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Orden eliminada satisfactoriamente'
  end

  def destroy_multiple
    Order.destroy redefine_ids(params[:multiple_ids])
    redirect_to orders_path(page: @current_page, search: @query), notice: "Ordenes eliminadas satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_params
      params.require(:order).permit(:refence)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.shopping_cart.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripción del módulo
		%p{align: "justify"} En este módulo se podrán visualizar todas las ordenes recibidas, tendrá permisos para ver cada orden de forma detallada, y será libre de eliminarlas.

app/views/orders/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to orders_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @order do |f|
					.row
						= f.input :kid_id
						= f.input :symphony_id
						= f.input :disc_name
						= f.input :disc_message, input_html: {class: "materialize-textarea"}
						= f.input :refence, input_html: {class: "materialize-textarea"}
						= f.input :quantity

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/orders/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Order
			= link_to edit_order_path(@order), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.shopping_cart.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label Orden N°
			.display-value= @order.id
		%hr
		%h6 Información del producto
		%hr
		- @order.articles.each do |article|
			.product
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.kid_id")
					.display-value= article.kid.name
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.symphony_id")
					.display-value= article.symphony.title
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.disc_name")
					.display-value= article.disc_name
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.disc_message")
					.display-value= article.disc_message
			%hr
		%h6 Información de Contacto
		%hr
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @order.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @order.email
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.phone")
			.display-value= @order.phone
		- unless @order.refence.blank?
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.refence")
				.display-value= @order.refence
		
	

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/orders/_listing.html.haml
%tr{ id: "row-#{order.id}" }
	- if can? :destroy_multiple, Order
		%td.item-check{style:"width: 10%"}
			= link_to "", order_path(order), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{order.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{order.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{order.id}" }
		%td{style:"width: 5%"}
			= link_to "", order_path(order, search: @query), remote: true, class: "show-row"
			%span
				= order.id
		%td{style:"width: 25%"}
			= link_to "", order_path(order, search: @query), remote: true, class: "show-row"
			%span
				= order.name
		%td{style:"width: 25%"}
			= link_to "", order_path(order, search: @query), remote: true, class: "show-row"
			%span
				= order.email
		%td{style:"width: 15%"}
			= link_to "", order_path(order, search: @query), remote: true, class: "show-row"
			%span
				= order.phone
		%td{style:"width: 30%"}
			= link_to "", order_path(order, search: @query), remote: true, class: "show-row"
			%span
				= order.created_at.strftime("%d-%m-%Y")
								
	%td{style:"width: 5%"}		
		= link_to order_path(order), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/orders/edit.html.haml
= title "Orders - editar | #{@order.id}"
= render 'form'

app/views/orders/index.html.haml
= title("Ordenes - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_order_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |order|
				= render 'listing', order: order
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado ordenes.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_order_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/orders/new.html.haml
= title "Ordenes - Nuevo"
= render 'form'

app/views/orders/show.html.haml
= title "Ordenes | #{@order.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Order
				= link_to order_path(@order), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: '¿Estas seguro de querer eliminar?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Order
				= link_to edit_order_path(@order), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to orders_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card
			%ul.list
				%h6 Información del producto
				%hr
				- @order.articles.each do |article|
					.product
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.kid_id")
							.display-value= article.kid.name
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.symphony_id")
							.display-value= article.symphony.title
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.disc_name")
							.display-value= article.disc_name
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.disc_message")
							.display-value= article.disc_message
					%hr
				%h6 Información de Contacto
				%hr
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value= @order.name
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.email")
					.display-value= @order.email
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.phone")
					.display-value= @order.phone

app/views/orders/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@order.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");