config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "/about", to: "frontend#about", as: :about
  get "/our-mision", to: "frontend#our_mision", as: :mision
  get "/contact", to: "frontend#contact_us", as: :contact
  get "/order/:symphony_id", to: "frontend#new_order", as: :new_order_frontend
  get "/verify-name", to: "frontend#verify_name", as: :verify_name
  post "/hear", to: "frontend#hear", as: :hear
  post "/order", to: "frontend#create_order", as: :create_order
  get :autocomplete_kid_name, to: "frontend#autocomplete_kid_name", as: :autocomplete_kid_name_orders

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :symphonies do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :orders do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple

    end

  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #contact_us
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'


end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  layout 'layouts/frontend/application'
  autocomplete :kid, :name

  def index
    @symphonies = Symphony.where(public: true)
  end

  def about
  end

  def our_mision
  end

  def our_products
  end

  def contact_us
    @message = KepplerContactUs::Message.new
  end

  def hear
    @symphony = Symphony.find(params[:symphony_id])
    @kid = Kid.find_by_name(params[:kid_name])

    respond_to do |format|
      format.js
    end
  end

  def new_order
    @symphony = Symphony.find(params[:symphony_id])
  end

  def create_order
    @symphonies = Symphony.where(public: true).order(:title)
    @order = Order.new(order_params)

    if @order.save
      OrderMailer.notification_client(@order).deliver_now
      OrderMailer.notification_admin(@order).deliver_now
      redirect_to root_path, notice: 'We have received your order, we will soon be communicating with you.'
    else
      flash[:alert] = 'There was an error in filling out the order, please check the entered data'
      render :new_order
    end
  end

  private

  def order_params
    params.require(:order).permit(:refence, :name, :email, :phone, articles_attributes: [:kid_id, :kid_name, :symphony_id, :disc_name, :disc_message, :_destroy])
  end
end

app/views/layouts/frontend/_footer.html.haml
.banner{ style: "background: #7363a8"}
	.container-textura
	.container-text
		.text
			%h1 GET IN TOUCH WITH US
			%ul#socials
				%li
					= link_to "mailto:information@casitakids.com" do
						.fa.fa-stack.fa-lg
							%i.fa.fa-circle.fa-stack-2x
							%i.fa.fa-envelope.fa-stack-1x#item-social
				%li
					= #link_to "https://instagram.com/casitakids7/", target: "_blank" do
					//.fa.fa-stack.fa-lg
					//	%i.fa.fa-circle.fa-stack-2x
					//	%i.fa.fa-instagram.fa-stack-1x#item-social
				%li
					= link_to "https://www.facebook.com/casitakids/", target: "_blank" do
						.fa.fa-stack.fa-lg
							%i.fa.fa-circle.fa-stack-2x
							%i.fa.fa-facebook.fa-stack-1x#item-social
.band-slice
	.brand
		Logos and brands are property of CASITAKIDS©2015
	.design.hidden-xs
		Diseñado por
		= link_to "http://www.behance.net/marisellap", target: "_blank" do
			Marisella Pacheco
	.dev
		Desarrollado por
		= link_to "http://slicegroup.xyz", target: "_blank" do
			= image_tag "frontend/slice.png"

	

app/views/layouts/frontend/_google_analytics.html.haml
- if Rails.env.production?
	:javascript
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-69910974-1', 'auto');
		ga('send', 'pageview');

app/views/layouts/frontend/_head.html.haml
%head
	%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
	%title= content_for?(:title) ? yield(:title) : 'Casita Kids. Personalized Children Music And More.'
	%meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Welcome to CASITAKIDS we are a leading and innovative company in the commercialization and distribution of musical contents personalized for children and girls of ages from 0 to 7 years. Emphasizing that in every song the name of his child will be the protagonist'}"}
	= stylesheet_link_tag 'frontend/application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'frontend/application', 'data-turbolinks-track' => true
	= render 'layouts/frontend/google_analytics'
	= favicon_link_tag "frontend/favicon.png"
	= csrf_meta_tags

app/views/layouts/frontend/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
	- if msg.is_a?(String)
		- if name.to_s == 'notice'
			:javascript
				swal("Good job!", "#{msg}", "success")
		- if name.to_s == 'alert' and (action_name.eql?("create_order") or action_name.eql?("contact_us"))
			:javascript
				swal("Error", "#{msg}", "error");
				$( document ).ready(function() {
					(function(){ window.scrollTo(0, document.getElementById("new_order").offsetTop); })();
				});

app/views/layouts/frontend/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default#front-navbar
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse
      %ul.nav.navbar-nav        
        = render 'layouts/frontend/navigation_links'

app/views/layouts/frontend/_navigation_links.html.haml
%li{ class: "visible-xs visible-sm" }
	= link_to 'Home'.html_safe, root_path
%li
	= link_to about_path, style: "padding: 0px;", class: "hidden-xs hidden-sm" do
		= image_tag "frontend/icono-violin.png", width: "80px;"
	= link_to 'About'.html_safe, about_path
%li
	= link_to mision_path, style: "padding: 0px;", class: "hidden-xs hidden-sm" do
		= image_tag "frontend/icono-trompeta.png", width: "80px;"
	= link_to 'Our Mission'.html_safe, mision_path
%li
	= link_to root_path, class: "hidden-xs hidden-sm" do
		= image_tag "frontend/casitakids-logo.png", id: "casitakids-logo"
%li
	= link_to is_index? ? "#symphonies" : root_path(anchor: "symphonies"), style: "padding: 0px;", class: "hidden-xs hidden-sm" do
		= image_tag "frontend/icono-guitarra.png", width: "80px;"
	= link_to 'Our Products'.html_safe, is_index? ? "#symphonies" : root_path(anchor: "symphonies")
%li
	= link_to contact_path, style: "padding: 0px;", class: "hidden-xs hidden-sm" do
		= image_tag "frontend/icono-microfono.png", width: "55px;"
	= link_to 'Contact Us'.html_safe, contact_path

app/views/layouts/frontend/application.html.haml
!!!
%html
	= render 'layouts/frontend/head' 
	%body
		%header
			= render 'layouts/frontend/navigation'
		%main{:role => "main"}
			= render 'layouts/frontend/messages'
			= yield
		%footer
			= render 'layouts/frontend/footer'
			
			