config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "/about", to: "frontend#about", as: :about
  get "/our-mision", to: "frontend#our_mision", as: :mision
  get "/contact", to: "frontend#contact_us", as: :contact
  get "/order/:symphony_id", to: "frontend#new_order", as: :new_order_frontend
  get "/verify-name", to: "frontend#verify_name", as: :verify_name
  post "/hear", to: "frontend#hear", as: :hear
  post "/order", to: "frontend#create_order", as: :create_order
  get :autocomplete_kid_name, to: "frontend#autocomplete_kid_name", as: :autocomplete_kid_name_orders

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :symphonies do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :orders do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple

    end

  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #contact_us
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'


end

app/models/symphony.rb
#Generado por keppler
require 'elasticsearch/model'
class Symphony < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mount_uploader :cover, CoverUploader
  mount_uploader :song, SongUploader
  has_many :articles
  validates_presence_of :cover, :song, :title, :description, :age, :price
  validates :price, numericality: { greater_than_or_equal_to: 1 }

  
  after_commit on: [:update] do
    __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:id, :price, :title] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      price:  self.price.to_s,
      title:  self.title
    }.as_json
  end

  def color
    case self.id
      when 1
        "primary"
      when 2
        "green"
      when 3
        "blue"
      else
        ["primary", "green", "blue"].sample
    end
  end

end
#Symphony.import

app/controllers/symphonies_controller.rb
#Generado con Keppler.
class SymphoniesController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_symphony, only: [:show, :edit, :update, :destroy]

  # GET /symphonies
  def index
    symphonies = Symphony.searching(@query).all
    @objects, @total = symphonies.page(@current_page), symphonies.size
    redirect_to symphonies_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /symphonies/1
  def show
  end

  # GET /symphonies/new
  def new
    @symphony = Symphony.new
  end

  # GET /symphonies/1/edit
  def edit
  end

  # POST /symphonies
  def create
    @symphony = Symphony.new(symphony_params)

    if @symphony.save
      redirect_to @symphony, notice: 'Symphony was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /symphonies/1
  def update
    if @symphony.update(symphony_params)
      redirect_to @symphony, notice: 'Sinfonía actualizada satisfactoriamente.'
    else
      render :edit
    end
  end

  # DELETE /symphonies/1
  def destroy
    @symphony.destroy
    redirect_to symphonies_url, notice: 'Symphony was successfully destroyed.'
  end

  def destroy_multiple
    Symphony.destroy redefine_ids(params[:multiple_ids])
    redirect_to symphonies_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_symphony
      @symphony = Symphony.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def symphony_params
      params.require(:symphony).permit(:cover, :price, :title, :description, :song, :age, :public, :store_url)
    end
end

app/helpers/symphonies_helper.rb
module SymphoniesHelper
end

app/views/symphonies/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.library_music.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripción del módulo
		%p{align: "justify"} En este módulo se podran ver de forma detallada cada sinonía precargada y de la misma forma solo se podrán modificar los datos de las sinfonías ya existente.

app/views/symphonies/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to symphonies_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @symphony do |f|
					.row
						= f.input :cover, :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						= f.input :title, label: "Título"
						= f.input :price, label: "Precio"
						%label{ style: "margin-left: 11px; font-size: 14px; position:relative; top: 12px;"} Descripción
						= f.input :description, label: false, as: :ckeditor, input_html: { :ckeditor => { :toolbar => 'mini'} }
						= f.input :song, label: "Canción", :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						= f.input :store_url, label: "Url del producto en la tienda online"
						= f.input :public, as: :checkbox_material, label: "¿Desea publicar esta sinfonía?"
						= f.input :age, as: :hidden, input_html: { value: "0-7" }


						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

- if @symphony.cover.file
	:javascript
		$('.file-path').first().val("#{@symphony.cover.file.filename}")

- if @symphony.song.file
	:javascript
		$('.file-path').last().val("#{@symphony.song.file.filename}")

app/views/symphonies/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Symphony
			= link_to edit_symphony_path(@symphony), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", 'data-no-turbolink' => true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.library_music.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-image
		= image_tag @symphony.cover
		%audio{ controls: "" }
			%source{ src: @symphony.song }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @symphony.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.price")
			.display-value= number_with_precision "#{@symphony.price}", precision: 2, separator: '.', delimiter: ','
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.title")
			.display-value= @symphony.title
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= sanitize(@symphony.description, tags: []).truncate(300)
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.age")
			.display-value= @symphony.age
	

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/symphonies/_listing.html.haml
%tr{ id: "row-#{symphony.id}" }
	- if can? :destroy_multiple, Symphony
		%td.item-check{style:"width: 10%"}
			= link_to "", symphony_path(symphony), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{symphony.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{symphony.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{symphony.id}" }

	%td{style:"width: 10%"}
		= link_to "", symphony_path(symphony, search: @query), remote: true, class: "show-row"
		%span
			= symphony.id
	%td{style:"width: 70%"}
		= link_to "", symphony_path(symphony, search: @query), remote: true, class: "show-row"
		%span
			= symphony.title
	%td{style:"width: 20%"}
		= link_to "", symphony_path(symphony, search: @query), remote: true, class: "show-row"
		%span
			= number_with_precision "#{symphony.price}", precision: 2, separator: '.', delimiter: ','
								
	%td{style:"width: 5%"}		
		= link_to symphony_path(symphony), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/symphonies/edit.html.haml
= title "Symphonies - editar | #{@symphony.id}"
= render 'form'

app/views/symphonies/index.html.haml
= title("Symphonies - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_symphony_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only", 'data-no-turbolink' => true do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |symphony|
				= render 'listing', symphony: symphony
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado sinfonías.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_symphony_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/symphonies/new.html.haml
= title "Symphonies - Nuevo"
= render 'form'

app/views/symphonies/show.html.haml
= title "Symphonies | #{@symphony.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Symphony
				= link_to symphony_path(@symphony), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Symphony
				= link_to edit_symphony_path(@symphony), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", 'data-no-turbolink' => true do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to symphonies_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card
			.img-card
				= image_tag @symphony.cover, width: "300px;"
				%audio{ controls: "" }
					%source{ src: @symphony.song }
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @symphony.id
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.price")
					.display-value.fs-body-1.tc-black-2= number_with_precision "#{@symphony.price}", precision: 2, separator: '.', delimiter: ','
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.title")
					.display-value.fs-body-1.tc-black-2= @symphony.title
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.description")
					.display-value.fs-body-1.tc-black-2= raw @symphony.description
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.age")
					.display-value.fs-body-1.tc-black-2= @symphony.age

app/views/symphonies/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@symphony.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");